const EX=[['pullups','Pullups'],['pushups','Pushups'],['dips','Dips'],['squats','Squats']];
const KEY='repforge-db-v7';const SCHEMA=7;const BACKUP_SCHEMA=3;const $=id=>document.getElementById(id);
const clone=o=>JSON.parse(JSON.stringify(o));
const iso=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const today=()=>iso(new Date());const addDays=(s,n)=>{const d=new Date(`${s}T12:00:00`);d.setDate(d.getDate()+n);return iso(d)};const fmt=s=>new Date(`${s}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'2-digit',year:'numeric'});
const fmtNum=n=>Number(n||0).toLocaleString();
const BASE_TARGETS={pullups:400,pushups:500,dips:200,squats:300};
const DEFAULT={schema:SCHEMA,logs:{},bulk:{pullups:{},pushups:{},dips:{},squats:{}},targetDefaults:clone(BASE_TARGETS),targetPeriods:[],targets:[{from:'2000-01-01',values:clone(BASE_TARGETS)}],daily:{},theme:'default',deletedEntries:{},deletedDaily:{},deletedBulk:{},deletedTargets:{},bulkMeta:{},targetDefaultsUpdatedAt:0,syncMeta:{lastSync:null,status:'offline'}};
function normalizeDb(x){
  const b=clone(DEFAULT),o=(x&&typeof x==='object')?x:{};
  const d={...b,...o,schema:SCHEMA,logs:o.logs&&typeof o.logs==='object'?o.logs:{},daily:o.daily&&typeof o.daily==='object'?o.daily:{},bulk:{...b.bulk,...(o.bulk||{})}};
  for(const [k] of EX)d.bulk[k]={...(o.bulk?.[k]||{})};
  let defaults={...BASE_TARGETS,...(o.targetDefaults||{})};
  let periods=Array.isArray(o.targetPeriods)?o.targetPeriods:[];
  if(!Array.isArray(o.targetPeriods)){
    const legacy=Array.isArray(o.targets)?o.targets:[];
    if(legacy.length){
      const first=legacy.find(t=>t.from==='2000-01-01')||legacy[0];
      defaults={...defaults,...(first?.values||{})};
      periods=legacy.filter(t=>t!==first).map(t=>({id:crypto.randomUUID(),from:t.from,to:null,values:{...t.values},label:'Legacy target change'}));
    }
  }
  d.targetDefaults=defaults; d.targetPeriods=periods; d.deletedEntries={...(o.deletedEntries||{})}; d.deletedTargets={...(o.deletedTargets||{})}; d.deletedDaily={...(o.deletedDaily||{})}; d.deletedBulk={...(o.deletedBulk||{})}; d.bulkMeta={...(o.bulkMeta||{})}; d.targetDefaultsUpdatedAt=Number(o.targetDefaultsUpdatedAt||0); d.syncMeta={...b.syncMeta,...(o.syncMeta||{})};
  d.targets=[{from:'2000-01-01',values:clone(defaults)},...periods.filter(x=>x&&x.from).map(x=>({from:x.from,values:{...defaults,...(x.values||{})}}))];
  return d;
}
function load(){try{return normalizeDb(JSON.parse(localStorage.getItem(KEY)||'null'))}catch{return clone(DEFAULT)}}let db=load();let selectedDate=today();let selectedEx='pullups';let chart=null;let customMode='repeat';let customRest=null;let restTimer=null;let timerState={phase:'READY',sec:0,round:0,running:false,timer:null};let historyMonth=new Date();
function touch(){return Date.now()}
function save(){db.schema=SCHEMA;localStorage.setItem(KEY,JSON.stringify(db)); if(window.RepForgeSync?.schedule) window.RepForgeSync.schedule()}
function dayTotal(d,k){return (db.logs[d]?.[k]||[]).reduce((a,e)=>a+(e.type==='repeat'?Number(e.reps||0)*Number(e.sets||0):Number(e.reps||0)),0)}
function lifetime(k){let x=0;for(const d of Object.keys(db.logs))x+=dayTotal(d,k);x+=Object.values(db.bulk[k]||{}).reduce((a,v)=>a+Number(v||0),0);return x}
function targetFor(d,k){
  let best={priority:0,from:'2000-01-01',value:Number(db.targetDefaults?.[k]||0)};
  for(const p of (db.targetPeriods||[])){
    if(!p.from||p.from>d||(p.to&&d>p.to)||p.values?.[k]===undefined)continue;
    const type=p.from===p.to?3:(p.to?2:1);
    const priority=type*100000000+Number(p.from.replaceAll('-',''));
    if(priority>=best.priority)best={priority,from:p.from,value:Number(p.values[k]||0)};
  }
  return best.value;
}
function activeDays(k=null){return Object.keys(db.logs).filter(d=>k?dayTotal(d,k)>0:EX.some(([e])=>dayTotal(d,e)>0)).length}
function streak(k=null, target=false){let d=selectedDate,s=0;while(true){const total=k?dayTotal(d,k):EX.reduce((a,[e])=>a+dayTotal(d,e),0);const ok=target?(k?total>=targetFor(d,k):EX.every(([e])=>dayTotal(d,e)>=targetFor(d,e))):total>0;if(!ok)break;s++;d=addDays(d,-1)}return s}
function status(d,k){const a=dayTotal(d,k),t=targetFor(d,k);return a===0?'none':t&&a>=t?(a>t?'over':'hit'):'short'}
function populateSelects(){const opts=EX.map(([k,n])=>`<option value="${k}">${n}</option>`).join('');$('analyticsExercise').innerHTML=opts;$('logExercise').innerHTML=opts;for(const id of ['thresholdYear','annualYear','reportYear','bulkYear']){$(id).innerHTML='';for(let y=new Date().getFullYear();y>=2000;y--){$(id).insertAdjacentHTML('beforeend',`<option value="${y}">${y}</option>`)}}$('reportMonth').innerHTML=Array.from({length:12},(_,i)=>`<option value="${i+1}">${new Date(2000,i,1).toLocaleString(undefined,{month:'long'})}</option>`).join('')}
function renderTabs(){ $('exerciseTabs').innerHTML=EX.map(([k,n])=>`<button class="${k===selectedEx?'active':''}" data-ex="${k}">${n}</button>`).join('');document.querySelectorAll('#exerciseTabs button').forEach(b=>b.onclick=()=>{selectedEx=b.dataset.ex;renderAll()})}
function renderLog(){renderTabs();$('datePicker').value=selectedDate;$('datePretty').textContent=fmt(selectedDate);const total=dayTotal(selectedDate,selectedEx);const life=lifetime(selectedEx);$('sessionTotal').textContent=fmtNum(total);$('lifetimeTotal').textContent=fmtNum(life);const t=targetFor(selectedDate,selectedEx),pct=t?Math.round(total/t*100):0;$('targetActual').textContent=`${fmtNum(total)} / ${fmtNum(t)}`;$('targetStatus').textContent=t?(total>=t?`${pct>=100?'Target achieved':'On target'} · ${pct}%`:`${pct}% of target`):'Target not set';$('targetPct').textContent=t?`${Math.min(999,pct)}%`:'—';$('targetRing').style.setProperty('--deg',`${Math.min(100,pct)*3.6}deg`);$('sessionCount').textContent=`${(db.logs[selectedDate]?.[selectedEx]||[]).length} entries`;$('sessionEntries').innerHTML=renderEntries();const info=db.daily[selectedDate]||{};$('dailyRpe').value=info.rpe||'';$('dailyNote').value=info.note||''}
function renderEntries(){const es=db.logs[selectedDate]?.[selectedEx]||[];if(!es.length)return `<div class="empty">No ${EX.find(x=>x[0]===selectedEx)[1].toLowerCase()} logged for this date.</div>`;return es.map(e=>{const reps=e.type==='repeat'?e.reps*e.sets:e.reps;const label=e.type==='repeat'?`${e.reps} reps × ${e.sets} sets`:`${e.reps} reps · single set`;return `<div class="sessionRow"><div class="sessionMain"><b>${label} = ${fmtNum(reps)}</b><span>${e.weight?`${e.weight} kg · `:''}${e.notes||''}</span></div><div class="sessionActions"><button data-edit="${e.id}">Edit</button></div><div class="sessionActions"><button data-del="${e.id}">Delete</button></div></div>`}).join('')}
function renderAnalytics(){const k=$('analyticsExercise').value||selectedEx;const p=Number(document.querySelector('#analyticsPeriod button.active')?.dataset.p||365);const end=selectedDate;const start=addDays(end,-p+1);const vals=[];for(let d=start;d<=end;d=addDays(d,1))vals.push({d,a:dayTotal(d,k),t:targetFor(d,k)});const total=vals.reduce((a,x)=>a+x.a,0),active=vals.filter(x=>x.a>0).length,avg=active?Math.round(total/active):0,best=Math.max(0,...vals.map(x=>x.a));$('analyticsMetrics').innerHTML=[['Total',fmtNum(total)],['Active days',active],['Average / active day',fmtNum(avg)],['Best day',fmtNum(best)]].map(x=>`<div class="metric"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');$('chartCaption').textContent=`${fmt(start)} → ${fmt(end)}`;drawChart(vals);renderWeekCompare(k);renderTargetPerformance(k,vals);renderThreshold(k);renderAnnual()}
function drawChart(vals){if(!window.Chart)return;const c=$('volumeChart').getContext('2d');if(chart)chart.destroy();const max=Math.max(1,...vals.map(x=>Math.max(x.a||0,x.t||0)));const suggested=Math.ceil(max*1.1/50)*50;chart=new Chart(c,{type:'line',data:{labels:vals.map(x=>x.d.slice(5)),datasets:[{label:'Actual',data:vals.map(x=>x.a>0?x.a:null),borderColor:getComputedStyle(document.body).getPropertyValue('--accent').trim(),backgroundColor:'transparent',tension:.25,spanGaps:false,pointRadius:0,borderWidth:2},{label:'Target',data:vals.map(x=>x.t||0),borderColor:'#677382',backgroundColor:'transparent',borderDash:[6,5],stepped:true,tension:0,pointRadius:0,borderWidth:1.5}]},options:{responsive:true,interaction:{mode:'index',intersect:false},plugins:{legend:{labels:{color:'#aab4c1'}},tooltip:{callbacks:{title:i=>`Date: ${i[0]?.label||''}`,label:c=>`${c.dataset.label}: ${c.raw===null?'No workout':fmtNum(c.raw)+' reps'}`}}},scales:{x:{ticks:{color:'#7f8a98',maxTicksLimit:8},grid:{color:'#1e252c'}},y:{beginAtZero:true,suggestedMax:suggested,ticks:{color:'#7f8a98'},grid:{color:'#1e252c'}}}}})}
function weekStats(k,offset){const end=addDays(selectedDate,-offset*7),start=addDays(end,-6);let total=0,days=0;for(let d=start;d<=end;d=addDays(d,1)){const a=dayTotal(d,k);total+=a;if(a)days++}return{total,days,avg:days?Math.round(total/days):0}}
function renderWeekCompare(k){const a=weekStats(k,0),b=weekStats(k,1),diff=b.total?Math.round((a.total-b.total)/b.total*100):null;$('weekCompare').innerHTML=[['Total',fmtNum(a.total),diff===null?'—':`${diff>=0?'+':''}${diff}%`],['Active days',a.days,`${a.days-b.days>=0?'+':''}${a.days-b.days}`],['Average',fmtNum(a.avg),`${a.avg-b.avg>=0?'+':''}${fmtNum(a.avg-b.avg)}`]].map(x=>`<div class="compareItem"><small>${x[0]}</small><b>${x[1]}</b><span class="${String(x[2]).startsWith('+')?'good':''}">${x[2]}</span></div>`).join('')}
function renderTargetPerformance(k,vals){const eligible=vals.filter(x=>x.t>0),met=eligible.filter(x=>x.a>=x.t).length,over=eligible.filter(x=>x.a>x.t).length,short=eligible.filter(x=>x.a<x.t&&x.a>0).length,miss=eligible.filter(x=>x.a===0).length,pct=eligible.length?Math.round(met/eligible.length*100):0;$('targetPerformance').innerHTML=`<div class="metricGrid"><div class="metric"><small>Target achieved</small><b>${pct}%</b></div><div class="metric"><small>Over-performed</small><b>${over}</b></div><div class="metric"><small>Short</small><b>${short}</b></div><div class="metric"><small>No workout</small><b>${miss}</b></div></div><div class="progressLine"><i style="width:${pct}%"></i></div>`}
function thresholdDays(k,y,n){const start=`${y}-01-01`,end=`${y}-12-31`,out=[];for(let d=start;d<=end;d=addDays(d,1)){if(dayTotal(d,k)>=n)out.push(d)}return out}
function renderThreshold(k){const y=Number($('thresholdYear').value),n=Number($('thresholdValue').value||0),ds=thresholdDays(k,y,n),avg=ds.length?Math.round(ds.reduce((a,d)=>a+dayTotal(d,k),0)/ds.length):0;let longest=0,run=0;for(let d=`${y}-01-01`;d<=`${y}-12-31`;d=addDays(d,1)){if(dayTotal(d,k)>=n){run++;longest=Math.max(longest,run)}else run=0}const best=Math.max(0,...ds.map(d=>dayTotal(d,k)));$('thresholdResult').innerHTML=`<div class="bigResult">${ds.length} days at or above ${fmtNum(n)} reps</div><div class="metricGrid" style="margin-top:14px"><div class="metric"><small>Average on threshold days</small><b>${fmtNum(avg)}</b></div><div class="metric"><small>Highest</small><b>${fmtNum(best)}</b></div><div class="metric"><small>Longest consecutive run</small><b>${longest}</b></div><div class="metric"><small>Annual lifetime bulk</small><b>${fmtNum(db.bulk[k]?.[y]||0)}</b></div></div>`}
function renderAnnual(){const y=Number($('annualYear').value),rows=EX.map(([k,n])=>{let daily=0,days=0,met=0;for(let d=`${y}-01-01`;d<=`${y}-12-31`;d=addDays(d,1)){const a=dayTotal(d,k);daily+=a;if(a)days++;if(a>=targetFor(d,k)&&targetFor(d,k)>0)met++}const bulk=Number(db.bulk[k]?.[y]||0);return{k,n,total:daily+bulk,daily,bulk,days,met,threshold:thresholdDays(k,y,targetFor(`${y}-12-31`,k)).length}});$('annualSummary').innerHTML=`<table class="annualTable"><tr><th>Exercise</th><th>Total</th><th>Active days</th><th>Target days</th><th>400+ days</th></tr>${rows.map(r=>`<tr><td>${r.n}</td><td>${fmtNum(r.total)}</td><td>${r.days}</td><td>${r.met}</td><td>${thresholdDays(r.k,y,400).length}</td></tr>`).join('')}</table>`}
function targetValues(d){return Object.fromEntries(EX.map(([k])=>[k,targetFor(d,k)]))}
function renderTargets(){
  const d=$('targetDate').value||selectedDate;
  const defs=db.targetDefaults||BASE_TARGETS;
  $('defaultTargetInputs').innerHTML=EX.map(([k,n])=>`<label>${n}<input id="def-${k}" type="number" min="0" value="${defs[k]??0}"></label>`).join('');
  const vals=targetValues(d);
  $('targetInputs').innerHTML=EX.map(([k,n])=>`<label>${n}<input id="tg-${k}" type="number" min="0" placeholder="Current: ${vals[k]??0}"></label>`).join('');
  renderTargetPeriods();
}
function renderTargetPeriods(){
  const ps=[...(db.targetPeriods||[])].sort((a,b)=>a.from.localeCompare(b.from)||String(a.to||'9999-12-31').localeCompare(String(b.to||'9999-12-31')));
  $('targetPeriodsList').innerHTML=ps.length?ps.map(p=>`<div class="targetPeriod"><div><b>${p.from}${p.to?` → ${p.to}`:' → ongoing'}</b><span>${EX.filter(([k])=>p.values?.[k]!==undefined).map(([k,n])=>`${n}: ${fmtNum(p.values[k])}/day`).join(' · ')||'No exercise targets'}</span></div><button class="sessionActions" data-target-del="${p.id}">Delete</button></div>`).join(''):'<div class="empty">No target overrides. Your defaults apply.</div>';
  document.querySelectorAll('[data-target-del]').forEach(b=>b.onclick=()=>{if(confirm('Delete this target period?')){const tid=b.dataset.targetDel;const old=(db.targetPeriods||[]).find(x=>x.id===tid);db.targetPeriods=db.targetPeriods.filter(x=>x.id!==tid);db.deletedTargets[tid]={id:tid,updatedAt:touch(),from:old?.from,to:old?.to};save();renderAll();toast('Target period deleted')}});
}
function renderHistory(){const y=historyMonth.getFullYear(),m=historyMonth.getMonth();$('monthLabel').textContent=new Date(y,m,1).toLocaleString(undefined,{month:'long',year:'numeric'});const first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),offset=first.getDay();let h='';for(let i=0;i<offset;i++)h+='<div class="calday out"></div>';for(let n=1;n<=days;n++){const d=iso(new Date(y,m,n)),all=EX.reduce((a,[k])=>a+dayTotal(d,k),0),met=EX.length&&EX.every(([k])=>targetFor(d,k)>0&&dayTotal(d,k)>=targetFor(d,k));const cls=all===0?'none':met?'hit':EX.some(([k])=>dayTotal(d,k)>targetFor(d,k))?'over':'short';h+=`<button class="calday ${d===today()?'today':''}" data-hd="${d}"><b>${n}</b><i class="dot ${cls}"></i></button>`}$('calendar').innerHTML=h;document.querySelectorAll('[data-hd]').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.hd;closeModal($('historyModal'));show('log');renderAll()});const recent=Object.keys(db.logs).filter(d=>Object.values(db.logs[d]||{}).some(a=>a.length)).sort().reverse().slice(0,30);$('historyList').innerHTML=recent.length?recent.map(d=>`<div class="historyItem"><div><b>${fmt(d)}</b><span>${EX.filter(([k])=>dayTotal(d,k)>0).map(([k,n])=>`${n}: ${fmtNum(dayTotal(d,k))}`).join(' · ')}</span></div><strong>${fmtNum(EX.reduce((a,[k])=>a+dayTotal(d,k),0))}</strong></div>`).join(''):'<div class="empty">No workout history yet.</div>'}
function renderBulk(){const y=Number($('bulkYear').value);$('bulkInputs').innerHTML=EX.map(([k,n])=>`<label>${n}<input id="bulk-${k}" type="number" min="0" value="${db.bulk[k]?.[y]||0}"></label>`).join('');const years=new Set();for(const [k] of EX)Object.keys(db.bulk[k]||{}).forEach(v=>years.add(v));$('bulkList').innerHTML=[...years].sort((a,b)=>b-a).map(yr=>`<div class="bulkYearRow"><b>${yr}</b>${EX.map(([k])=>`<span>${EX.find(x=>x[0]===k)[1]} ${fmtNum(db.bulk[k]?.[yr]||0)}</span>`).join('')}</div>`).join('')||'<div class="empty">No historical bulk entries yet.</div>'}
function records(){let h='';for(const [k,n] of EX){let maxSet=0,maxWeighted={w:0,r:0},bestDay=0,bestDate='';for(const d of Object.keys(db.logs)){for(const e of db.logs[d]?.[k]||[]){const r=e.type==='repeat'?e.reps:e.reps;if(r>maxSet)maxSet=r;if(Number(e.weight||0)>maxWeighted.w||(Number(e.weight||0)===maxWeighted.w&&r>maxWeighted.r))maxWeighted={w:Number(e.weight||0),r}}const a=dayTotal(d,k);if(a>bestDay){bestDay=a;bestDate=d}}h+=`<div class="panel"><h2>${n}</h2><div class="recordGrid"><div class="recordCard"><small>Max reps in single set</small><b>${fmtNum(maxSet)}</b></div><div class="recordCard"><small>Heaviest weighted set</small><b>${maxWeighted.w?`${maxWeighted.w} kg × ${maxWeighted.r}`:'—'}</b></div><div class="recordCard"><small>Highest daily total</small><b>${fmtNum(bestDay)}</b><small>${bestDate||''}</small></div><div class="recordCard"><small>Lifetime total</small><b>${fmtNum(lifetime(k))}</b></div></div></div>`}$('recordsContent').innerHTML=h}
function themes(){const ts=[['default','Forge'],['ember','Ember'],['ice','Ice'],['violet','Violet'],['steel','Steel'],['forest','Forest']];$('themes').innerHTML=ts.map(([k,n])=>`<button data-theme="${k}"><b>${n}</b><small style="display:block;color:var(--muted);margin-top:5px">${k==='default'?'Lime / black':k}</small></button>`).join('');document.querySelectorAll('#themes button').forEach(b=>b.onclick=()=>{db.theme=b.dataset.theme;applyTheme();save()})}
function applyTheme(){document.body.dataset.theme=db.theme==='default'?'':db.theme}
function openModal(m){m.classList.add('open')}function closeModal(m){m.classList.remove('open')}
function show(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view));document.querySelectorAll('.bottomnav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='analytics')renderAnalytics()}
function renderAll(){renderLog();if($('analyticsExercise')){$('analyticsExercise').value=selectedEx;renderAnalytics()}renderHistory();renderBulk();records();renderTargets();themes()}
function startRest(){clearInterval(restTimer);let sec=30;$('restSeconds').textContent='00:30';$('restToast').classList.remove('hidden');restTimer=setInterval(()=>{sec--;if(sec<=0){clearInterval(restTimer);$('restToast').classList.add('hidden');beep()}else $('restSeconds').textContent=`00:${String(sec).padStart(2,'0')}`},1000)}
function beep(){try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=880;g.gain.value=.05;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.18)}catch{}}
function editEntry(id){const e=(db.logs[selectedDate]?.[selectedEx]||[]).find(x=>x.id===id);if(!e)return;openModal($('entryModal'));$('logDate').value=selectedDate;$('logExercise').value=selectedEx;if(e.type==='repeat'){setMode('repeat');$('rps').value=e.reps;$('setCount').value=e.sets;$('repeatWeight').value=e.weight||0}else{setMode('single');$('singleReps').value=e.reps;$('singleWeight').value=e.weight||0}$('entryNote').value=e.notes||'';$('saveEntry').dataset.edit=id;$('entryTitle').textContent='Edit workout';$('repeatTotal').textContent=(+$('rps').value||0)*(+$('setCount').value||0)}
function setMode(m){customMode=m;document.querySelectorAll('.mode button').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('repeatForm').hidden=m!=='repeat';$('singleForm').hidden=m!=='single'}
function reportRange(){const type=$('reportType').value,y=Number($('reportYear').value),m=Number($('reportMonth').value),q=Number($('reportQuarter').value);if(type==='Annual')return{start:`${y}-01-01`,end:`${y}-12-31`,title:`RepForge Annual Report ${y}`};if(type==='Quarterly'){const sm=(q-1)*3;return{start:`${y}-${String(sm+1).padStart(2,'0')}-01`,end:iso(new Date(y,sm+3,0)),title:`RepForge Q${q} ${y}`};}return{start:`${y}-${String(m).padStart(2,'0')}-01`,end:iso(new Date(y,m,0)),title:`RepForge ${new Date(y,m-1,1).toLocaleString(undefined,{month:'long'})} ${y}`}}
function generateReport(){const r=reportRange();const rows=EX.map(([k,n])=>{let actual=0,target=0,days=0,met=0;for(let d=r.start;d<=r.end;d=addDays(d,1)){const a=dayTotal(d,k);actual+=a;target+=targetFor(d,k);if(a)days++;if(a>=targetFor(d,k)&&targetFor(d,k)>0)met++}const bulkYears=[...Object.keys(db.bulk[k]||{})].filter(y=>`${y}-01-01`>=r.start&&`${y}-12-31`<=r.end);actual+=bulkYears.reduce((a,y)=>a+Number(db.bulk[k][y]||0),0);return[n,actual,target,days,met]});if(window.jspdf?.jsPDF){const {jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(20);doc.text(r.title,15,18);doc.setFontSize(10);doc.text(`${fmt(r.start)} — ${fmt(r.end)}`,15,26);let y=40;doc.text('Exercise',15,y);doc.text('Total',75,y);doc.text('Target',105,y);doc.text('Active days',135,y);doc.text('Target days',170,y);y+=8;rows.forEach(row=>{doc.text(String(row[0]),15,y);doc.text(fmtNum(row[1]),75,y);doc.text(fmtNum(row[2]),105,y);doc.text(String(row[3]),135,y);doc.text(String(row[4]),170,y);y+=8});doc.save(`${r.title.replaceAll(' ','_')}.pdf`)}else{const w=open();w.document.write(`<html><body style="font-family:Arial;padding:40px"><h1>${r.title}</h1><p>${fmt(r.start)} — ${fmt(r.end)}</p><table border="1" cellpadding="8"><tr><th>Exercise</th><th>Total</th><th>Target</th><th>Active days</th><th>Target days</th></tr>${rows.map(x=>`<tr>${x.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</table><script>setTimeout(()=>print(),400)<\/script></body></html>`);w.document.close()}}
function timerRender(){$('timerPhase').textContent=timerState.phase;$('timerDisplay').textContent=`${String(Math.floor(timerState.sec/60)).padStart(2,'0')}:${String(timerState.sec%60).padStart(2,'0')}`;$('timerRound').textContent=`Round ${timerState.round} / ${Number($('rounds').value||0)}`;$('timerStart').textContent=timerState.running?'Pause':'Start'}
function timerStart(){if(timerState.running){clearInterval(timerState.timer);timerState.running=false;timerRender();return}const prep=Number($('prep').value||0),work=Number($('work').value||30),rest=Number($('rest').value||30),rounds=Number($('rounds').value||8);if(!timerState.sec){timerState.phase=prep?'PREP':'WORK';timerState.sec=prep||work;timerState.round=1}timerState.running=true;timerState.timer=setInterval(()=>{timerState.sec--;if(timerState.sec<=0){if(timerState.phase==='PREP'){timerState.phase='WORK';timerState.sec=work;beep()}else if(timerState.phase==='WORK'){if(timerState.round>=rounds){timerState.phase='DONE';timerState.running=false;clearInterval(timerState.timer);beep()}else if(rest){timerState.phase='REST';timerState.sec=rest;beep()}else{timerState.round++;timerState.sec=work;beep()}}else{timerState.round++;timerState.phase='WORK';timerState.sec=work;beep()}}timerRender()},1000);timerRender()}
function backupStats(x){let days=0,entries=0,total=0;for(const d of Object.keys(x.logs||{})){let has=false;for(const [k] of EX){const es=x.logs[d]?.[k]||[];entries+=es.length;total+=es.reduce((a,e)=>a+(e.type==='repeat'?Number(e.reps||0)*Number(e.sets||0):Number(e.reps||0)),0);if(es.length)has=true}if(has)days++}for(const [k] of EX)total+=Object.values(x.bulk?.[k]||{}).reduce((a,v)=>a+Number(v||0),0);return{days,entries,total}}
function exportBackup(){const payload={app:'RepForge',backupSchema:BACKUP_SCHEMA,exportedAt:new Date().toISOString(),data:normalizeDb(db)};const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`RepForge_Full_Backup_${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Full backup exported')}
function importBackup(file){const r=new FileReader();r.onload=()=>{try{const raw=JSON.parse(r.result),x=raw?.app==='RepForge'&&raw.data?raw.data:raw;if(!x.logs||!Array.isArray(x.targets))throw Error('invalid');const restored=normalizeDb(x),s=backupStats(restored);if(!confirm(`RESTORE FULL BACKUP\n\nWorkout days: ${s.days}\nSession entries: ${s.entries}\nLifetime reps: ${fmtNum(s.total)}\n\nThis replaces the current data on this device. Continue?`))return;db=restored;save();renderAll();toast('Everything restored successfully')}catch(e){toast('Invalid or incompatible RepForge backup')}};r.readAsText(file)}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
// Navigation
populateSelects();applyTheme();$('analyticsExercise').value=selectedEx;$('annualYear').value=new Date().getFullYear();$('thresholdYear').value=new Date().getFullYear();$('reportYear').value=new Date().getFullYear();$('reportMonth').value=new Date().getMonth()+1;$('bulkYear').value=new Date().getFullYear();
document.querySelectorAll('.bottomnav button').forEach(b=>b.onclick=()=>show(b.dataset.view));$('themeQuick').onclick=()=>openModal($('appearanceModal'));$('syncOpen').onclick=()=>openModal($('syncModal'));$('syncMoreBtn').onclick=()=>openModal($('syncModal'));$('datePicker').onchange=e=>{if(e.target.value){selectedDate=e.target.value;renderAll()}};$('prevDay').onclick=()=>{selectedDate=addDays(selectedDate,-1);renderAll()};$('nextDay').onclick=()=>{selectedDate=addDays(selectedDate,1);renderAll()};$('historyBtn').onclick=()=>openModal($('historyModal'));
$('openEntry').onclick=()=>{openModal($('entryModal'));$('logDate').value=selectedDate;$('logExercise').value=selectedEx;$('entryTitle').textContent='Log workout';delete $('saveEntry').dataset.edit;setMode('repeat')};$('singleSetBtn').onclick=()=>{$('openEntry').click();setMode('single')};$('logExercise').onchange=e=>selectedEx=e.target.value;$('rps').oninput=$('setCount').oninput=()=>$('repeatTotal').textContent=(Number($('rps').value)||0)*(Number($('setCount').value)||0);
document.querySelectorAll('.mode button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('saveEntry').onclick=()=>{const d=$('logDate').value,k=$('logExercise').value;if(!d)return toast('Choose a date');if(!db.logs[d])db.logs[d]={};if(!db.logs[d][k])db.logs[d][k]=[];const id=$('saveEntry').dataset.edit;let e;if(customMode==='repeat'){const r=Number($('rps').value),s=Number($('setCount').value);if(!r||!s)return toast('Enter reps and sets');e={id:id||crypto.randomUUID(),type:'repeat',reps:r,sets:s,weight:Number($('repeatWeight').value||0),notes:$('entryNote').value||'',updatedAt:touch(),...(id?{}:{createdAt:touch()})}}else{const r=Number($('singleReps').value);if(!r)return toast('Enter reps');e={id:id||crypto.randomUUID(),type:'single',reps:r,sets:1,weight:Number($('singleWeight').value||0),notes:$('entryNote').value||'',updatedAt:touch(),...(id?{}:{createdAt:touch()})}}if(id){const i=db.logs[d][k].findIndex(x=>x.id===id);if(i>=0)db.logs[d][k][i]=e}else db.logs[d][k].push(e);save();selectedDate=d;selectedEx=k;closeModal($('entryModal'));renderAll();startRest();toast(id?'Workout updated':'Workout added')};
$('sessionEntries').addEventListener('click',e=>{const ed=e.target.closest('[data-edit]'),del=e.target.closest('[data-del]');if(ed)editEntry(ed.dataset.edit);if(del&&confirm('Delete this set entry?')){const delId=del.dataset.del;db.logs[selectedDate][selectedEx]=db.logs[selectedDate][selectedEx].filter(x=>x.id!==delId);db.deletedEntries[delId]={id:delId,updatedAt:touch()};save();renderAll();toast('Entry deleted')}});
$('dailyRpe').onchange=e=>{db.daily[selectedDate]={...(db.daily[selectedDate]||{}),rpe:e.target.value,updatedAt:touch()};save()};$('dailyNote').onchange=e=>{db.daily[selectedDate]={...(db.daily[selectedDate]||{}),note:e.target.value,updatedAt:touch()};save()};$('skipRest').onclick=()=>{clearInterval(restTimer);$('restToast').classList.add('hidden')};
$('analyticsExercise').onchange=()=>renderAnalytics();document.querySelectorAll('#analyticsPeriod button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#analyticsPeriod button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderAnalytics()});$('thresholdValue').oninput=()=>renderThreshold($('analyticsExercise').value);$('thresholdYear').onchange=()=>renderThreshold($('analyticsExercise').value);$('annualYear').onchange=renderAnnual;
$('prevMonth').onclick=()=>{historyMonth.setMonth(historyMonth.getMonth()-1);renderHistory()};$('nextMonth').onclick=()=>{historyMonth.setMonth(historyMonth.getMonth()+1);renderHistory()};
document.querySelectorAll('[data-modal]').forEach(b=>b.onclick=()=>openModal($(`${b.dataset.modal}Modal`)));document.querySelectorAll('.close').forEach(b=>b.onclick=()=>closeModal(b.closest('.modal')));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m)}));
$('targetDate').value=selectedDate;
$('saveDefaults').onclick=()=>{const v={};EX.forEach(([k])=>v[k]=Number($(`def-${k}`).value||0));db.targetDefaults=v;db.targetDefaultsUpdatedAt=touch();save();renderAll();toast('Default daily targets saved')};
$('saveTargets').onclick=()=>{const from=$('targetDate').value||selectedDate,v={};EX.forEach(([k])=>{const raw=$(`tg-${k}`).value;if(raw!=='')v[k]=Number(raw)});if(!Object.keys(v).length)return toast('Enter at least one exercise target');const to=from;db.targetPeriods=(db.targetPeriods||[]).filter(x=>!(x.from===from&&x.to===to));db.targetPeriods.push({id:crypto.randomUUID(),from,to,values:v,label:'Single day',updatedAt:touch()});save();closeModal($('targetsModal'));renderAll();toast(`Target override saved for ${from}`)};
$('targetDate').onchange=renderTargets;
$('periodStart').value=selectedDate;$('periodEnd').value='';
$('saveTargetPeriod').onclick=()=>{const from=$('periodStart').value,to=$('periodEnd').value||null;if(!from)return toast('Choose a start date');if(to&&to<from)return toast('End date must be on or after start date');const v={};EX.forEach(([k])=>{const val=$(`period-${k}`).value;if(val!=='')v[k]=Number(val)});if(!Object.keys(v).length)return toast('Enter at least one exercise target');db.targetPeriods=(db.targetPeriods||[]).filter(p=>!(p.from===from&&p.to===to));db.targetPeriods.push({id:crypto.randomUUID(),from,to,values:v,label:'Target period',updatedAt:touch()});save();renderAll();toast('Target period saved')};
$('periodStart').onchange=renderPeriodInputs;$('periodPreset').onchange=()=>{const mode=$('periodPreset').value,from=$('periodStart').value||selectedDate;$('periodEnd').value=mode==='ongoing'?'':mode==='year'?`${from.slice(0,4)}-12-31`:''};
function renderPeriodInputs(){const vals=targetValues($('periodStart').value||selectedDate);$('periodTargetInputs').innerHTML=EX.map(([k,n])=>`<label>${n}<input id="period-${k}" type="number" min="0" placeholder="${vals[k]??0}"></label>`).join('')}

$('bulkYear').onchange=renderBulk;$('saveBulk').onclick=()=>{const y=$('bulkYear').value;EX.forEach(([k])=>{db.bulk[k][y]=Number($(`bulk-${k}`).value||0);db.bulkMeta[`${k}_${y}`]=touch()});save();renderAll();toast(`Historical totals saved for ${y}`)};
$('exportData').onclick=exportBackup;$('importData').onchange=e=>{if(e.target.files[0])importBackup(e.target.files[0]);e.target.value=''};$('clearData').onclick=()=>{if(confirm('DELETE ALL REPFORGE DATA? This cannot be undone unless you have a backup.')){localStorage.removeItem(KEY);db=clone(DEFAULT);save();renderAll();toast('All data deleted')}};
$('generateReport').onclick=generateReport;$('timerStart').onclick=timerStart;$('timerReset').onclick=()=>{clearInterval(timerState.timer);timerState={phase:'READY',sec:0,round:0,running:false,timer:null};timerRender()};$('timerMode').onchange=e=>{if(e.target.value==='Tabata'){$('prep').value=10;$('work').value=20;$('rest').value=10;$('rounds').value=8}else{$('prep').value=10;$('work').value=30;$('rest').value=30;$('rounds').value=8}};
// Restore legacy V1 backup shape if present under the old key.
try{const legacy=localStorage.getItem('repforge-db-v5')||localStorage.getItem('repforge-db-v4');if(!localStorage.getItem(KEY)&&legacy){db=normalizeDb(JSON.parse(legacy));save()}}catch{}
renderPeriodInputs();renderAll();timerRender();if(window.RepForgeSync?.setup)RepForgeSync.setup();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
